services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/home/node
    container_name: todo-frontend-dev
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080/api/
  debug-helper:
    image: busybox
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
  server:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/home/node
    container_name: todo-backend-dev
    environment:
      - MONGO_URL=mongodb://admin:admin@mongo:27017/todos
      - REDIS_URL=//redis:6379
      - PORT=4000
  mongo:
    image: mongo:4.4.10-focal
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo-todo-backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: todos
  redis:
    image: redis
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis-todo-backend
    command: ["redis-server", "--appendonly", "yes"]
